# .streamlit/secrets.toml

[connections.snowflake]
account = "xxx"
user = "mohanreddypal"
password = "Mohan#5619717"
role = "SYSDAMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
